version: "3.9"

networks:
	mercado-solidario-network:
		driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3316:3316"
    networks:
      - mercado-solidario-network
      
    mercadosolidario-api:
    	image: mercadosolidario-api
    	environment:
    		HOST: mercadosolidario-mysql
    	ports:
    		- "8080:8080"
    	networks:
    		- mercado-solidario-network
    	depends_on:
    		- mercadosolidario-mysql